services:
  nats:
    image: nats:alpine
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats:/data
    command: "-js --sd /data"
    
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    volumes:
      - minio:/data
    ports:
      - 4223:9000
      - 4224:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: x9ZotJrg5euEp976rG
    command: server --console-address ":9001" /data
    
volumes:
  nats:
  minio: