services:
  nats:
    image: nats:alpine
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - data:/data
    command: "-js --sd /data"
    
volumes:
  data: