name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    - name: build
      run: dotnet build --configuration Release

    - name: nats
      run: docker run -d -p 4222:4222 -p 8222:8222 nats -js
        
    - name: test
      run: dotnet test --configuration Release
